#!/bin/bash
# =============================================================================
# Vendefoul Wolf (Devuan + OpenRC) Router Setup Script
# This script turns a fresh Vendefoul OpenRC server into a full router with:
#   • Pi-hole for network-wide DNS-based ad/tracker blocking
#   • Internal LAN using 10.x.x.x addresses (10.0.0.0/24)
#   • WAN interface connected via DHCP to upstream router at 192.168.1.1
# =============================================================================
# Run as root on a fresh Vendefoul Wolf server installation.
# BEFORE RUNNING:
#   1. Identify your two Ethernet ports:
#      - Run: ip -brief link show
#      - WAN port = the one physically connected to 192.168.1.1
#      - LAN port = the one for your internal network
#   2. Edit the variables below if your interface names differ from eth0/eth1.
# =============================================================================

set -euo pipefail

# ========================== CONFIGURATION ==========================
WAN_INTERFACE="eth0"          # WAN port (connects to 192.168.1.1) - uses DHCP
LAN_INTERFACE="eth1"          # LAN port (serves internal clients)
LAN_IP="10.0.0.1"             # Router's IP on the internal network
LAN_SUBNET="10.0.0.0/24"      # Internal subnet (10.x.x.x addresses)
LAN_NETMASK="255.255.255.0"   # Subnet mask for 10.0.0.0/24

# Optional: change these if you prefer a different 10.x.x.x range
# e.g. LAN_IP="10.42.0.1"  LAN_SUBNET="10.42.0.0/24"
# ==================================================================

echo "=== Vendefoul OpenRC Router Setup Starting ==="
echo "WAN interface (to 192.168.1.1): $WAN_INTERFACE"
echo "LAN interface (internal 10.x.x.x): $LAN_INTERFACE"
echo "Internal router IP: $LAN_IP"
echo ""

# 1. Update system
echo "1. Updating package lists and upgrading system..."
apt-get update -qq
apt-get upgrade -y -qq

# 2. Install required packages
echo "2. Installing dependencies (iptables-persistent, curl, etc.)..."
apt-get install -y -qq \
    curl \
    iptables-persistent \
    net-tools \
    dnsutils \
    whiptail

# 3. Backup and configure /etc/network/interfaces (Devuan/OpenRC style)
echo "3. Configuring network interfaces..."
cp /etc/network/interfaces /etc/network/interfaces.bak 2>/dev/null || true

cat > /etc/network/interfaces <<EOF
# Vendefoul OpenRC Router - auto-generated by setup script
# Loopback
auto lo
iface lo inet loopback

# WAN - connects to upstream router at 192.168.1.1 (DHCP client)
auto $WAN_INTERFACE
iface $WAN_INTERFACE inet dhcp

# LAN - internal 10.x.x.x network (static)
auto $LAN_INTERFACE
iface $LAN_INTERFACE inet static
    address $LAN_IP
    netmask $LAN_NETMASK
    # No gateway on LAN side
EOF

# Ensure networking service is enabled (OpenRC)
rc-update add networking default 2>/dev/null || true

# Bring interfaces up
echo "   Bringing interfaces up..."
ifdown --force "$WAN_INTERFACE" "$LAN_INTERFACE" 2>/dev/null || true
ifup "$WAN_INTERFACE" "$LAN_INTERFACE"

echo "   Waiting for WAN DHCP lease from 192.168.1.1..."
sleep 5
ip addr show "$WAN_INTERFACE" | grep -q "inet " || echo "   WARNING: WAN did not receive IP. Check cable/connection."

# 4. Enable IP forwarding (required for routing)
echo "4. Enabling IP forwarding..."
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-router.conf
sysctl -p /etc/sysctl.d/99-router.conf

# 5. Set up iptables NAT + forwarding + firewall (router rules)
echo "5. Setting up NAT, forwarding, and basic firewall..."
# Flush existing rules
iptables -F
iptables -t nat -F
iptables -t mangle -F

# NAT masquerade for outbound traffic
iptables -t nat -A POSTROUTING -o "$WAN_INTERFACE" -j MASQUERADE

# Allow forwarding LAN -> WAN
iptables -A FORWARD -i "$LAN_INTERFACE" -o "$WAN_INTERFACE" -j ACCEPT

# Allow established/related connections back
iptables -A FORWARD -i "$WAN_INTERFACE" -o "$LAN_INTERFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT

# Drop everything else (basic security)
iptables -A FORWARD -j DROP

# Save rules persistently (iptables-persistent / netfilter-persistent)
netfilter-persistent save

# Enable the persistent service on boot (OpenRC)
rc-update add netfilter-persistent default 2>/dev/null || true

# 6. Install Pi-hole (DNS blocking)
echo "6. Installing Pi-hole for network-wide DNS ad-blocking..."
echo ""
echo "   Pi-hole installer will now run. You will be prompted:"
echo "     • Select interface → choose $LAN_INTERFACE"
echo "     • Upstream DNS provider → recommended: Cloudflare (1.1.1.1) or Quad9"
echo "     • Install web admin interface → Yes"
echo "     • Web password → set one (remember it!)"
echo ""
read -p "Press Enter to continue with Pi-hole installation..."

# Run official installer (works on Devuan/OpenRC with minor adaptations)
curl -sSL https://install.pi-hole.net | bash

# 7. Final touches
echo "7. Final configuration and service enabling..."
# Ensure Pi-hole services start at boot (OpenRC)
rc-update add lighttpd default 2>/dev/null || true
rc-update add pihole-FTL default 2>/dev/null || true

# Restart services
rc-service networking restart
rc-service netfilter-persistent restart
rc-service lighttpd restart 2>/dev/null || true
rc-service pihole-FTL restart 2>/dev/null || true

echo ""
echo "=== SETUP COMPLETE! ==="
echo ""
echo "Router is now ready:"
echo "   • WAN: $WAN_INTERFACE connected to 192.168.1.1 (DHCP)"
echo "   • LAN: $LAN_INTERFACE at $LAN_IP / $LAN_NETMASK (10.x.x.x range)"
echo "   • NAT + routing enabled and persistent"
echo "   • Pi-hole installed for DNS ad-blocking"
echo ""
echo "NEXT STEPS (highly recommended):"
echo "1. Connect a client to the LAN port"
echo "2. Access Pi-hole web admin: http://$LAN_IP/admin"
echo "   - Log in with the password you set"
echo "3. In Pi-hole dashboard → Settings → DHCP:"
echo "   - Enable DHCP server"
echo "   - Range: 10.0.0.100 to 10.0.0.250 (or any 10.x.x.x range you prefer)"
echo "   - Router (gateway) IP: $LAN_IP"
echo "   - DNS server: $LAN_IP"
echo "4. Save and apply. Clients will now get 10.x.x.x IPs, use this router as gateway,"
echo "   and get automatic DNS blocking via Pi-hole."
echo ""
echo "Optional:"
echo "   • Change Pi-hole upstream DNS in web UI if desired"
echo "   • SSH into router and run: pihole -up  (to update Pi-hole later)"
echo "   • Check status: rc-service pihole-FTL status"
echo ""
echo "Your Vendefoul OpenRC server is now a fully functional router with Pi-hole!"
echo "Enjoy ad-free browsing across your entire network."
