[bar]
order = [ "default", "Dock" ]

    [bar.Dock]
    auto_hide = true
    background_opacity = 0.71999998390674591
    border_width = 2.5
    center = [ "launcher", "taskbar" ]
    enabled = true
    end = []
    layer = "overlay"
    margin_edge = 4
    margin_ends = 450
    position = "bottom"
    reserve_space = false
    scale = 2.1000000238418579
    start = []
    thickness = 64

    [bar.default]
    enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1800.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    locked_timeout = 600.0
    timeout = 3600.0

[location]
address = "oxford, arkansas"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-3",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 224.0
    box_width = 464.0
    cx = 1608.0
    cy = 912.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        bands = 32
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 224.0
    box_width = 464.0
    cx = 316.0
    cy = 912.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[nightlight]
enabled = true

[shell]
app_icon_colorize = false
font_family = "Noto Sans"
polkit_agent = true

    [shell.screenshot]
    save_to_file         = true
    directory            = "~/Pictures/screenshots"
    filename_pattern     = "screenshot_%Y%m%d_%H%M%S"
    copy_to_clipboard    = true
    freeze_screen        = true
    confirm_region       = false
    remember_last_region = false
    show_cursor          = false
    annotate             = true
    close_on_copy        = true
    close_on_save        = true

    [shell.launcher.providers.emoji]
    global = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "dysfunctional"

[wallpaper]
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/mshalom/Pictures/wallpapers/lake-of-ozarks-2-2055256900.jpg"

    [wallpaper.last]
    path = "/home/mshalom/Pictures/wallpapers/lake-of-ozarks-2-2055256900.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/mshalom/Pictures/wallpapers/lake-of-ozarks-2-2055256900.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/mshalom/Pictures/wallpapers/lake-of-ozarks-2-2055256900.jpg"

[weather]
unit = "imperial"

[widget.taskbar]
pinned = [ "steam" ]

[widget.tray]
hide_passive = false
